services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mobilesolutions
    depends_on:
      - mongodb
    networks:
      - app-network
    command: uvicorn app:app --host 0.0.0.0 --reload

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=mobilesolutions

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
